# Generated by Django 5.1.6 on 2025-04-27 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_data_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlbum',
            fields=[
                ('pic_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('pic_url_original', models.URLField(blank=True, max_length=500, null=True)),
                ('pic_url_annotated', models.URLField(blank=True, max_length=500, null=True)),
                ('pic_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_album',
                'ordering': ['-pic_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DetectedLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=255)),
                ('x', models.FloatField(help_text='X coordinate of top-left corner')),
                ('y', models.FloatField(help_text='Y coordinate of top-left corner')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('confidence', models.FloatField()),
                ('pic', models.ForeignKey(db_column='pic_id', on_delete=django.db.models.deletion.CASCADE, related_name='detected_landmarks', to='td_data_processor.useralbum')),
            ],
            options={
                'db_table': 'detected_landmarks',
                'ordering': ['-confidence'],
            },
        ),
    ]
