# Generated by Django 5.1.6 on 2025-05-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_data_processor', '0002_useralbum_detectedlandmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedImage',
            fields=[
                ('converted_pic_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('converted_pic_url', models.URLField(blank=True, max_length=500, null=True)),
                ('direction', models.CharField(help_text="e.g. 'sunny2rainy' or 'rainy2sunny'", max_length=50)),
                ('converted_pic_timestamp', models.DateTimeField(auto_now_add=True)),
                ('original_pic_id', models.ForeignKey(db_column='pic_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='converted_images', to='td_data_processor.useralbum')),
            ],
            options={
                'db_table': 'converted_images',
                'ordering': ['-converted_pic_timestamp'],
            },
        ),
    ]
